TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Models/AutenticacaoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FurbotWeb.Models
{
    public class AutenticacaoViewModel
    {
        public string Login { get; set; }

        public string Senha { get; set; }

        public string DivParaExibicao { get; set; }

        public Guid UID { get; set; }

        [Required(ErrorMessage = "A nova senha deve ser informada.")]
        public string NovaSenha { get; set; }

        [Required(ErrorMessage = "A confirmação da nova senha deve ser informada.")]
        [Compare("NovaSenha", ErrorMessage = "A confirmação de senha não confere com a nova senha informada.")]
        public string ConfirmacaoSenha { get; set; }

        public string CaminhoRetorno { get; set; }
    }
}

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Models/RecuperarSenhaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FurbotWeb.Models
{
    public class RecuperarSenhaViewModel
    {
        public string Login { get; set; }
        public string Mensagem { get; set; }
        public string Status { get; set; }
    }
}

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Controllers/AutenticacaoController.cs
using FurbotWeb.Dominio;
using FurbotWeb.Dominio.Enum;
using FurbotWeb.Models;
using FurbotWeb.Negocio;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace FurbotWeb.Controllers
{
    public class AutenticacaoController : Controller
    {
        private AutenticacaoViewModel _viewModel;

        [HttpGet]
        public ActionResult Index(string retornoUrl = null)
        {
            try
            {
                if (FurbotWebSession.IsAuthenticated)
                    if (FurbotWebSession.Current.IsProfessor)
                        return Redirect(RouteTable.Routes.GetVirtualPath(null, null).VirtualPath + "Professor");
                    else if (FurbotWebSession.Current.IsAluno)
                        return Redirect(RouteTable.Routes.GetVirtualPath(null, null).VirtualPath + "Aluno");

                this._viewModel = new AutenticacaoViewModel
                {
                    CaminhoRetorno = retornoUrl,
                    DivParaExibicao = "login"
                };
                return View(this._viewModel);
            }
            catch (Exception)
            {
                return Redirect("~/Erros/InternalServer");
            }
        }

        [HttpPost]
        public JsonResult Logar(AutenticacaoViewModel viewModel, string municipio = null)
        {
            object retorno;
            var usuarioServico = new UsuarioServico();
            try
            {
                var usuario = usuarioServico.Obter(viewModel.Login);

                if (usuario != null)
                {
                    if (usuario.TentativasAcesso < 4)
                    {
                        if (usuario.Ativo)
                        {
                            //GetHashSHA1()
                            if (viewModel.Senha.Equals(usuario.Senha))
                            {
                                usuario.TentativasAcesso = 0;
                                FurbotWebSession.Login(usuario);
                                retorno = new { Logado = true, CaminhoRetorno = ConfigurarPaginaRetorno(viewModel, usuario) };
                            }
                            else
                            {
                                usuario.TentativasAcesso++;

                                if (usuario.TentativasAcesso >= 4)
                                {
                                    usuario.Ativo = false;
                                    retorno =
                                        new
                                        {
                                            Modal = true,
                                            Mensagem = "Você excedeu o número de tentativas de acesso e seu acesso foi suspenso.",
                                            Solucao = "Clique em Esqueceu a senha? para redefinir a senha de acesso ao sistema."
                                        };
                                }
                                else
                                    retorno =
                                        new
                                        {
                                            Senha = true,
                                            Mensagem = "A senha está incorreta."
                                        };
                            }

                            usuarioServico.Atualizar(usuario);
                        }
                        else //usuário inativo
                            retorno =
                                new
                                {
                                    Modal = true,
                                    Mensagem = "Usuário inativo.",
                                    Solucao = "Clique em solicitar acesso ao sistema para requisitar acesso."
                                };
                    }
                    else
                    {//usuário já excedeu o número de tentativas de acesso
                        retorno =
                            new
                            {
                                Modal = true,
                                Mensagem = "Você excedeu o número de tentativas de acesso.",
                                Solucao = "Clique em Esqueceu a senha? para redefinir a senha de acesso ao sistema."
                            };
                    }
                }
                else //usuário não encontrado para o login informado
                    retorno =
                        new
                        {
                            Login = true,
                            Mensagem = "Login inválido."
                        };
            }
            catch (Exception e)
            {
                retorno = new { Logado = false, Mensagem = e.Message };
            }

            return Json(retorno);
        }

        private string ConfigurarPaginaRetorno(AutenticacaoViewModel viewModel, Usuario usuario)
        {
            string caminhoRetorno = string.Empty;
            if (viewModel.CaminhoRetorno != null)
                caminhoRetorno = viewModel.CaminhoRetorno;
            else if (usuario.Tipo == Tipo.Aluno)
            {
                caminhoRetorno = RouteTable.Routes.GetVirtualPath(null, null).VirtualPath + "Aluno";
            }
            else if (usuario.Tipo == Tipo.Professor)
                caminhoRetorno = RouteTable.Routes.GetVirtualPath(null, null).VirtualPath + "Professor";

            return caminhoRetorno;
        }

        [HttpPost]
        public ActionResult EnviarEmailSolicitacao(RecuperarSenhaViewModel viewModel)
        {
            //ValidarRecuperarSenhaViewModel(viewModel);

            //if (!ModelState.IsValid)
            //    return Json(new { Mensagem = ModelState.ToMessageValidationManager().Messages().First().Message, Status = "Falha" });

            var emailPrincipal = new UsuarioServico().ObterEmail(viewModel.Login);

            if (emailPrincipal == null)
                return PartialView("ErroAoEnviarSolicitacao");

            //var request = recuperarSenhaServico.CriarRequestDeAlteracao(viewModel.Usuario);

            //ServiceContext.GetService<IServicoEmail>().EnviarEmailRecuperarSenhaParaProcessamento(identidadeJuridica.NomeJuridico(),
            //    emailPrincipal.Endereco, ObterUrlBase(), request.UID);

            return PartialView("SolicitacaoEnviada");
        }

        [HttpGet]
        public ActionResult NovaSenha(string reset)
        {
            Guid chaveAcesso;
            if (!Guid.TryParse(reset, out chaveAcesso))
                return View("Index", new AutenticacaoViewModel { DivParaExibicao = "erroGuid" });

            //var request = recuperarSenhaServico.BuscarRequestParaAlteracao(chaveAcesso);

            //if (request == null)
            //    return View("Index", new AutenticacaoViewModel { DivParaExibicao = "erroGuid" });

            //if (!recuperarSenhaServico.RequestEstaValida(request))
            //    return View("Index", new AutenticacaoViewModel { DivParaExibicao = "solicitacaoExpirada" });

            return View("NovaSenha", new AutenticacaoViewModel { Login = "request.CpfCnpj", UID = chaveAcesso });
        }

        [HttpPost]
        public ActionResult AlterarSenha(AutenticacaoViewModel model)
        {
            if (model.UID == Guid.Empty)
                return View("Index", new AutenticacaoViewModel { DivParaExibicao = "erroGuid" });

            //var request = recuperarSenhaServico.BuscarRequestParaAlteracao(model.UID);

            //if (request == null)
            //    return View("Index", new AutenticacaoViewModel { DivParaExibicao = "erroGuid" });

            //if (!recuperarSenhaServico.RequestEstaValida(request))
            //    return View("Index", new AutenticacaoViewModel { DivParaExibicao = "solicitacaoExpirada" });

            var usuarioServico = new UsuarioServico();

            var usuario = usuarioServico.Obter(model.Login);

            usuario.Senha = model.NovaSenha.GetHashSHA1();
            if (usuario.Tipo == Tipo.Professor)
            {
                usuario.Ativo = true;
                usuario.TentativasAcesso = 0;
            }

            usuarioServico.Atualizar(usuario);
            //recuperarSenhaServico.RemoverRequestConcluida(repositorio, request);

            FurbotWebSession.Login(usuario);

            return Redirect(ConfigurarPaginaRetorno(new AutenticacaoViewModel(), usuario));
        }

        public void Sair()
        {
            FurbotWebSession.Logoff();
            Response.Redirect("~/Autenticacao");
        }

        [HttpPost]
        public ActionResult Salvar()
        {
            var anoSemestre = new AnoSemestre()
            {
                Ano = 2016,
                Semetre = Semestre.I
            };

            var disciplina = new Disciplina()
            {
                Nome = "Introdução à computação"
            };

            var turmaA = new Turma()
            {
                Disciplina = disciplina,
                AnoSemetre = anoSemestre
            };

            new TurmaServico().Adicionar(turmaA);

            var usuarioServico = new UsuarioServico();

            Pessoa mauricio = new Pessoa()
            {
                CPF = "12312312312",
                DataNascimento = new DateTime(1969, 09, 24),
                Email = "mau.capo@gmail.com",
                Nome = "Maurício Capobianco Lopes"
            };

            Usuario professor = new Usuario()
            {
                Ativo = true,
                Tipo = Tipo.Aluno,
                Login = "mlopes",
                Senha = "123",
                Pessoa = mauricio,
                Turma = turmaA
            };
            usuarioServico.Adicionar(professor);

            Pessoa heloisa = new Pessoa
            {
                CPF = "08623127951",
                DataNascimento = new DateTime(1993, 12, 11),
                Email = "manitur.heloisa@gmail.com",

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Views/Autenticacao/ErroGuidEmail.cshtml
<div id="Painel-Conteudo-Login">
    <h2 class="Erro">ERRO DE IDENTIFICAÇÃO!</h2>
    <p>Por algum motivo o usuário solicitado não foi encontrado, verifique seu e-mail para repetir o procedimento ou recupere a senha novamente para um receber um novo e-mail.</p>
    <a href="#" style="float: left; margin: 0 auto;" onclick="MostraFormRecuperarSenha();">Tentar novamente.</a>
</div>

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Views/Autenticacao/Index.cshtml
@model FurbotWeb.Models.AutenticacaoViewModel
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<script>
    function SetaDivVisivel(id) {
        $("#" + id).css('display', 'block');
    }

    $(function () {
        SetaDivVisivel('@Model.DivParaExibicao');
    });
</script>

<div id="login" class="Painel-Conteudo">
    @{ Html.RenderPartial("Login", Model);}
</div>
<div id="recuperarSenha" class="Painel-Conteudo" style="display: none;">
    @{ Html.RenderPartial("RecuperarSenha", new FurbotWeb.Models.RecuperarSenhaViewModel());}
</div>
<div id="erroGuid" class="Painel-Conteudo" style="display: none;">
    @{ Html.RenderPartial("ErroGuidEmail");}
</div>
<div id="solicitacaoExpirada" class="Painel-Conteudo" style="display: none;">
    @{ Html.RenderPartial("RequestAlteracaoExpirada");}
</div>
<div id="emailEnviado" class="Painel-Conteudo Borda-Esquerda" style="display: none;">
</div>

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Views/Autenticacao/Login.cshtml
@model FurbotWeb.Models.AutenticacaoViewModel

<script src="~/Scripts/configuracoes.js"></script>
<script src="~/Scripts/login.js"></script>
<script type="text/javascript">
    $(function () {
        urlLogin = "@Href("~/Autenticacao/Logar")";
        urlRotaPadrao = "@Href("~/Autenticacao/")";
        jsonViewModel = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model))
        viewModel = new loginViewModel();
        ko.applyBindings(viewModel);
        ConfigurarValidacao();

        if (getReturnUrl()) {
            $('div#Janela-Modal').on('dialogclose', function () {
                $("div#Janela-Modal").empty();
            });
            $('div#Janela-Modal').modalAdvertencia('Realize o login para executar a ação solicitada.', 'Por razões de segurança você deverá efetuar o login.').dialog('open');
        }
    });

    function MostraFormRecuperarSenha() {
        $("#Botao-RecuperarSenha").removeClass("Botao-Login-Entrando");
        $("#Botao-RecuperarSenha").val("Recuperar senha");
        SetaDivVisivel('recuperarSenha');
        $("#UsuarioRecuperarSenha").focus();
    }
</script>

@using (Html.BeginForm("Logar", "Autenticacao", FormMethod.Post, new { Id = "FormularioLogin" }))
{
    <div id="Painel-Conteudo-Login">
        <div class="Campos">
            <label>Login</label>
            @Html.TextBoxFor(m => m.Login, new { maxlength = "14" })
            @Html.ValidationMessageFor(m => m.Login)
        </div>
        <div class="Campos">
            <label>Senha</label>
            @Html.TextBoxFor(m => m.Senha, new
               {
                   type = "password",
                   maxlength = "50",
                   data_val = "true",
                   data_val_valid_word = "A senha não pode conter o caracter do sinal maior(<) e o sinal menor(>)."
               })
            @Html.ValidationMessageFor(m => m.Senha)
        </div>
        <input type="submit" id="Botao-Entrar" class="Botao-Login" value="Entrar" data-bind="click: logar" />
        <br />
        <br />
        <a href="javascript:void(0);" onclick="MostraFormRecuperarSenha();">>> Recupere sua senha</a>
        <br />
        <a href="~/Cadastro">>> Cadastre-se</a>
    </div>
}

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Views/Autenticacao/RecuperarSenha.cshtml
@model FurbotWeb.Models.RecuperarSenhaViewModel

<style>
    .Botao-Recuperar {
        width: 172px;
    }
</style>

<script type="text/javascript">
    $(function () {
        var form = $("#FormularioRecuperarSenha");
        $('#UsuarioRecuperarSenha').focus().setMask({ mask: '99999999999999', autoTab: false });

        form.submit(function (e) {
            e.preventDefault();
            $('.input-validation-error').removeClass('input-validation-error');
            $('.field-validation-error').children().html('');
            $("#Botao-RecuperarSenha").removeClass("Botao-Recuperar-Senha");
            $("#Botao-RecuperarSenha").addClass("Botao-Login-Entrando Botao-Recuperar-Senha");
            $("#Botao-RecuperarSenha").val("Enviando E-mail");

            $.post(form.attr('action'), form.serialize(), function (retorno) {
                if (retorno.Status == 'Falha') {
                    mensagemValidacaoCampos('UsuarioRecuperarSenha', retorno.Mensagem, form);
                    mensagemValidacaoCampos('Usuario', retorno.Mensagem, form);
                    alterarBotaoRecuperarSenha();
                }
                else if (retorno.Status == 'Modal') {
                    $("#Janela-Modal").modalAdvertencia(retorno.Mensagem, retorno.Solucao).dialog("open");
                    alterarBotaoRecuperarSenha();
                }
                else {
                    $("#Botao-RecuperarSenha").addClass("Botao-Login-Entrando Botao-Recuperar-Senha");
                    $("#Botao-RecuperarSenha").val("Enviando E-mail");

                    SetaDivVisivel('emailEnviado');
                    $("#emailEnviado").html(retorno);

                    form[0].reset();
                }
            });
        });
    });

    function MostraFormLogin() {
        $('.input-validation-error').removeClass('input-validation-error');
        $('.field-validation-error').children().html('');
        $("#UsuarioRecuperarSenha").val('');
        $('#UsuarioRecuperarSenha').removeClass('input-validation-error');
        var elementoSpan = $("#FormularioRecuperarSenha").find('[data-valmsg-for$="Usuario"]');
        elementoSpan.removeClass('field-validation-error');
        elementoSpan.html('');
        SetaDivVisivel('login');
        $("#Usuario").focus();
    }

    function alterarBotaoRecuperarSenha() {
        $("#Botao-RecuperarSenha").removeClass("Botao-Login-Entrando Botao-Recuperar-Senha");
        $("#Botao-RecuperarSenha").addClass("Botao-Recuperar-Senha");
        $("#Botao-RecuperarSenha").val("Recuperar senha");
    }

</script>

@using (Html.BeginForm("EnviarEmailSolicitacao", "Autenticacao", FormMethod.Post, new { Id = "FormularioRecuperarSenha" }))
{
    <div id="Painel-Conteudo-Login">
        <div class="Campos" style="margin-bottom: 11px;">
            <label>Login</label>
            @Html.TextBoxFor(m => m.Login, new { maxlength = "14", Id = "UsuarioRecuperarSenha" })
            @Html.ValidationMessageFor(m => m.Login)
        </div>
        <input type="submit" id="Botao-RecuperarSenha" class="Botao-Recuperar-Senha" value="Recuperar senha" />
        <a href="#" onclick=" MostraFormLogin();" style="float: right;">Voltar</a>
    </div>
}

TCC2016-1-HeloisaKopsch/Blockly/FurbotWeb/Views/Autenticacao/RequestAlteracaoExpirada.cshtml
<div id="Painel-Conteudo-Login">
    <h2 class="Erro">PRAZO DA SOLICITAÇÃO TERMINOU!</h2>
    <p>Você precisa repetir o procedimento, clique em solicitar acesso para receber um novo e-mail.</p>
    <a href="#" style="float: left; margin: 0 auto;" onclick="MostraFormRecuperarSenha();">Tentar novamente.</a>
</div>